language: c

before_install:
  - sudo add-apt-repository -y ppa:saiarcot895/chromium-beta
  - sudo apt-get update
  - sudo pip install cpp-coveralls

install: sudo apt-get install ninja-build

script: gcc -v && ./configure && ninja -v && ./base && ./waiters && ./channel && ./locks && ./pool && ./asyncio && ./bench && ./test_recurser && ./wait && ./log_stdout && ./ct

compiler:
  - gcc
  - clang

env:
  - CFLAGS="-O3"
  - CFLAGS="-O0 --coverage -DCOVERAGE" LDFLAGS="--coverage" COVERAGE=1

after_success:
  - '[ -n "$COVERAGE" ] && coveralls --exclude test --exclude include --exclude src/http_parser.c'
